version: 0.2

phases:
  build:
    commands:
      - echo running test ..
      - echo $NODE_ENV
      - docker-compose run -d -p 5432:5432 ptushki-postgres-test
      - node -v
      - npm ci
      - npm run test
      - npm run test:coverage
  post_build:
    commands:
      - docker-compose down
      - printf '[{"name":"ptushki-api","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitionstest.json
artifacts:
  files: imagedefinitionstest.json
